### ISSUE TITLE
Pypy3 from COPR doesn't work

### ISSUE THREAD

**Issue by frenzymadness** [frenzymadness/fedora-python-tox#12]
During build with Python 3.7 I found out that there is something wrong with the newest Pypy3 from COPR.

```shell
$ docker run --rm -it -v $PWD:/src -w /src frenzymadness/fedora-python-tox
# Pypy is ok
pypy installed: cffi==1.10.1,greenlet==0.4.12,py==1.5.2,pytest==3.2.5,readline==6.2.4.1
pypy runtests: PYTHONHASHSEED='618530766'
pypy runtests: commands[0] | pytest
========================================== test session starts ==========================================
platform linux2 -- Python 2.7.13[pypy-5.8.0-final], pytest-3.2.5, py-1.5.2, pluggy-0.4.0
rootdir: /src, inifile:
collected 10 items                                                                                       

test_fac.py ..........

======================================= 10 passed in 0.05 seconds =======================================
# But Pypy3 not
Traceback (most recent call last):
  File "/usr/bin/tox", line 11, in <module>
    load_entry_point('tox==2.7.0', 'console_scripts', 'tox')()
  File "/usr/lib/python3.6/site-packages/tox/session.py", line 39, in main
    retcode = Session(config).runcommand()
  File "/usr/lib/python3.6/site-packages/tox/session.py", line 392, in runcommand
    return self.subcommand_test()
  File "/usr/lib/python3.6/site-packages/tox/session.py", line 543, in subcommand_test
    if self.setupenv(venv):
  File "/usr/lib/python3.6/site-packages/tox/session.py", line 461, in setupenv
    envlog.set_python_info(commandpath)
  File "/usr/lib/python3.6/site-packages/tox/result.py", line 49, in set_python_info
    "import sys; "
  File "/usr/lib/python3.6/site-packages/py/_path/local.py", line 714, in sysexec
    stdout, stderr,)
py.process.cmdexec.Error: ExecutionFailed: 1  /src/.tox/pypy3/bin/python
debug: WARNING: Library path not found, using compiled-in sys.path, with
debug: WARNING: sys.prefix = '/builddir/build/BUILD/pypy2-v5.8.0-src'
debug: WARNING: Make sure the pypy binary is kept inside its tree of files.
debug: WARNING: It is ok to create a symlink to it from somewhere else.
debug: OperationError:
debug:  operror-type: ImportError
debug:  operror-value: No module named os
```

Because I don't have time to inspect it now, I decided to remove COPR repo from Dockerfile and use standard Pypy3 from Fedora repositories.. https://github.com/frenzymadness/fedora-python-tox/commit/ff004e71d68b123ff8a56f3af674f022980a9e58

@hroncok IMHO you know Pypy better than me.

**Comment by hroncok** [comment]
This says `/builddir/build/BUILD/pypy2-v5.8.0-src`. That doesn't sound like pypy3.

I will examine the Travis log if you give it to me.

This is my local machine:

```
[example_project (master %)]$ pwd
.../fedora-python-tox/example_project

[example_project (master %)]$ rpm -q pypy3
pypy3-5.10.1-1.fc27.x86_64

[example_project (master %)]$ rpm -q python3-tox
python3-tox-2.7.0-2.fc27.noarch

[example_project (master %)]$ tox
py26 recreate: .../fedora-python-tox/example_project/.tox/py26
py26 installdeps: pytest < 3.3
py26 installed: DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6,argparse==1.4.0,ordereddict==1.1,py==1.4.34,pytest==3.2.5
py26 runtests: PYTHONHASHSEED='2614337979'
py26 runtests: commands[0] | pytest
====================================================================================================== test session starts ======================================================================================================
platform linux4 -- Python 2.6.9, pytest-3.2.5, py-1.4.34, pluggy-0.4.0
rootdir: .../fedora-python-tox/example_project, inifile:
collected 10 items                                                                                                                                                                                                               

test_fac.py ..........

=================================================================================================== 10 passed in 0.02 seconds ===================================================================================================
py27 recreate: .../fedora-python-tox/example_project/.tox/py27
py27 installdeps: pytest < 3.3
py27 installed: py==1.5.2,pytest==3.2.5
py27 runtests: PYTHONHASHSEED='2614337979'
py27 runtests: commands[0] | pytest
====================================================================================================== test session starts ======================================================================================================
platform linux2 -- Python 2.7.14, pytest-3.2.5, py-1.5.2, pluggy-0.4.0
rootdir: .../fedora-python-tox/example_project, inifile:
collected 10 items                                                                                                                                                                                                               

test_fac.py ..........

=================================================================================================== 10 passed in 0.02 seconds ===================================================================================================
py33 recreate: .../fedora-python-tox/example_project/.tox/py33
py33 installdeps: pytest < 3.3
py33 installed: py==1.4.34,pytest==3.2.5
py33 runtests: PYTHONHASHSEED='2614337979'
py33 runtests: commands[0] | pytest
====================================================================================================== test session starts ======================================================================================================
platform linux -- Python 3.3.7, pytest-3.2.5, py-1.4.34, pluggy-0.4.0
rootdir: .../fedora-python-tox/example_project, inifile:
collected 10 items                                                                                                                                                                                                               

test_fac.py ..........

=================================================================================================== 10 passed in 0.03 seconds ===================================================================================================
py34 recreate: .../fedora-python-tox/example_project/.tox/py34
py34 installdeps: pytest < 3.3
py34 installed: py==1.5.2,pytest==3.2.5
py34 runtests: PYTHONHASHSEED='2614337979'
py34 runtests: commands[0] | pytest
====================================================================================================== test session starts ======================================================================================================
platform linux -- Python 3.4.7, pytest-3.2.5, py-1.5.2, pluggy-0.4.0
rootdir: .../fedora-python-tox/example_project, inifile:
collected 10 items                                                                                                                                                                                                               

test_fac.py ..........

=================================================================================================== 10 passed in 0.04 seconds ===================================================================================================
py35 recreate: .../fedora-python-tox/example_project/.tox/py35
py35 installdeps: pytest < 3.3
py35 installed: py==1.5.2,pytest==3.2.5
py35 runtests: PYTHONHASHSEED='2614337979'
py35 runtests: commands[0] | pytest
====================================================================================================== test session starts ======================================================================================================
platform linux -- Python 3.5.4, pytest-3.2.5, py-1.5.2, pluggy-0.4.0
rootdir: .../fedora-python-tox/example_project, inifile:
collected 10 items                                                                                                                                                                                                               

test_fac.py ..........

=================================================================================================== 10 passed in 0.03 seconds ===================================================================================================
py36 recreate: .../fedora-python-tox/example_project/.tox/py36
py36 installdeps: pytest < 3.3
py36 installed: py==1.5.2,pytest==3.2.5
py36 runtests: PYTHONHASHSEED='2614337979'
py36 runtests: commands[0] | pytest
====================================================================================================== test session starts ======================================================================================================
platform linux -- Python 3.6.3, pytest-3.2.5, py-1.5.2, pluggy-0.4.0
rootdir: .../fedora-python-tox/example_project, inifile:
collected 10 items                                                                                                                                                                                                               

test_fac.py ..........

=================================================================================================== 10 passed in 0.02 seconds ===================================================================================================
py37 create: .../fedora-python-tox/example_project/.tox/py37
py37 installdeps: pytest < 3.3
py37 installed: py==1.5.2,pytest==3.2.5
py37 runtests: PYTHONHASHSEED='2614337979'
py37 runtests: commands[0] | pytest
====================================================================================================== test session starts ======================================================================================================
platform linux -- Python 3.7.0a2, pytest-3.2.5, py-1.5.2, pluggy-0.4.0
rootdir: .../fedora-python-tox/example_project, inifile:
collected 10 items                                                                                                                                                                                                               

test_fac.py ..........

=================================================================================================== 10 passed in 0.02 seconds ===================================================================================================
pypy recreate: .../fedora-python-tox/example_project/.tox/pypy
pypy installdeps: pytest < 3.3
pypy installed: cffi==1.10.1,greenlet==0.4.12,py==1.5.2,pytest==3.2.5,readline==6.2.4.1
pypy runtests: PYTHONHASHSEED='2614337979'
pypy runtests: commands[0] | pytest
====================================================================================================== test session starts ======================================================================================================
platform linux2 -- Python 2.7.13[pypy-5.8.0-final], pytest-3.2.5, py-1.5.2, pluggy-0.4.0
rootdir: .../fedora-python-tox/example_project, inifile:
collected 10 items                                                                                                                                                                                                               

test_fac.py ..........

=================================================================================================== 10 passed in 0.04 seconds ===================================================================================================
pypy3 recreate: .../fedora-python-tox/example_project/.tox/pypy3
pypy3 installdeps: pytest < 3.3
pypy3 installed: cffi==1.11.2,greenlet==0.4.12,py==1.5.2,pytest==3.2.5,readline==6.2.4.1
pypy3 runtests: PYTHONHASHSEED='2614337979'
pypy3 runtests: commands[0] | pytest
====================================================================================================== test session starts ======================================================================================================
platform linux -- Python 3.5.3[pypy-5.10.1-final], pytest-3.2.5, py-1.5.2, pluggy-0.4.0
rootdir: .../fedora-python-tox/example_project, inifile:
collected 10 items                                                                                                                                                                                                               

test_fac.py ..........

=================================================================================================== 10 passed in 0.07 seconds ===================================================================================================
jython recreate: .../fedora-python-tox/example_project/.tox/jython
jython installdeps: pytest < 3.3
jython installed: py==1.5.2,pytest==3.2.5
jython runtests: PYTHONHASHSEED='2614337979'
jython runtests: commands[0] | pytest
============================= test session starts ==============================
platform java1.8.0_151 -- Python 2.7.1, pytest-3.2.5, py-1.5.2, pluggy-0.4.0
rootdir: .../fedora-python-tox/example_project, inifile:
collected 10 items                                                              

test_fac.py ..........

========================== 10 passed in 0.96 seconds ===========================
____________________________________________________________________________________________________________ summary ____________________________________________________________________________________________________________
  py26: commands succeeded
  py27: commands succeeded
  py33: commands succeeded
  py34: commands succeeded
  py35: commands succeeded
  py36: commands succeeded
  py37: commands succeeded
  pypy: commands succeeded
  pypy3: commands succeeded
  jython: commands succeeded
  congratulations :)
```

**Comment by hroncok** [comment]
Also work in copr for me:

```
[fedora-python-tox (master %)]$ git checkout e711ad3
...
HEAD is now at e711ad3... Add Python 3.7 also to example project

[fedora-python-tox ((e711ad3...) %)]$ docker build -t frenzymadness/fedora-python-tox .
Sending build context to Docker daemon 132.7 MB
Step 1/6 : FROM fedora:27
Trying to pull repository docker.io/library/fedora ... 
sha256:25f7dac76b2c88d8b7e0b1d6213d3406e77c7f230bfa1e66bd1cbb81a944eaaf: Pulling from docker.io/library/fedora
a8ee583972c2: Pull complete 
Digest: sha256:25f7dac76b2c88d8b7e0b1d6213d3406e77c7f230bfa1e66bd1cbb81a944eaaf
Status: Downloaded newer image for docker.io/fedora:27
 ---> 422dc563ca32
Step 2/6 : LABEL maintainer "Lumír 'Frenzy' Balhar <frenzy.madness@gmail.com>"
 ---> Running in 282b94580a30
 ---> 78bf5d2d40fa
Removing intermediate container 282b94580a30
Step 3/6 : RUN curl https://copr.fedorainfracloud.org/coprs/g/python/pypy35/repo/fedora-27/group_python-pypy35-fedora-27.repo     -o /etc/yum.repos.d/group_python-pypy35-fedora-27.repo
 ---> Running in 59fc8cb42bd8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   339  100   339    0     0    339      0  0:00:01 --:--:--  0:00:01   389
 ---> f2094915c0d2
Removing intermediate container 59fc8cb42bd8
Step 4/6 : RUN dnf install -y     --setopt=tsflags=nodocs     --setopt=deltarpm=false     findutils     jython     pypy-devel     pypy3-devel     python2-devel     python3-devel     python26     python27     python33     python34     python35     python36     python37     python2-pip     python3-pip     /usr/bin/tox     /usr/bin/virtualenv     gcc     gcc-c++     && dnf clean all
 ---> Running in bd4dbd4aa644
Fedora 27 - x86_64 - Updates                    5.6 MB/s |  16 MB     00:02    
Fedora 27 - x86_64                              7.8 MB/s |  58 MB     00:07    
Copr repo for pypy35 owned by @python           159 kB/s | 247 kB     00:01    
Last metadata expiration check: 0:00:01 ago on Fri Jan 19 13:00:57 2018.
Package python3-3.6.2-13.fc27.x86_64 is already installed, skipping.
Package python3-pip-9.0.1-11.fc27.noarch is already installed, skipping.
Dependencies resolved.
================================================================================
 Package                     Arch   Version           Repository           Size
================================================================================
Installing:
 findutils                   x86_64 1:4.6.0-14.fc27   fedora              522 k
 gcc                         x86_64 7.2.1-2.fc27      fedora               21 M
 gcc-c++                     x86_64 7.2.1-2.fc27      fedora               11 M
 jython                      noarch 2.7.1-3.fc27      fedora               10 M
 pypy-devel                  x86_64 5.8.0-3.fc27      fedora               73 k
 pypy3-devel                 x86_64 5.10.1-1.fc27     group_python-pypy35  64 k
 python2-devel               x86_64 2.7.14-6.fc27     updates             408 k
 python2-pip                 noarch 9.0.1-14.fc27     updates             1.8 M
 python2-virtualenv          noarch 15.1.0-2.fc27     fedora              1.7 M
 python26                    x86_64 2.6.9-10.fc27     updates             9.8 M
 python3-devel               x86_64 3.6.3-2.fc27      updates             866 k
 python3-tox                 noarch 2.7.0-2.fc27      fedora               95 k
 python33                    x86_64 3.3.7-2.fc27      updates              13 M
 python34                    x86_64 3.4.7-2.fc27      updates              15 M
 python35                    x86_64 3.5.4-2.fc27      updates              20 M
 python37                    x86_64 3.7.0-0.1.a2.fc27 updates              20 M
Upgrading:
 gdbm                        x86_64 1:1.13-6.fc27     updates             158 k
 python3                     x86_64 3.6.3-2.fc27      updates              68 k
 python3-libs                x86_64 3.6.3-2.fc27      updates             8.6 M
Installing dependencies:
...

Transaction Summary
================================================================================
Install  112 Packages
Upgrade    3 Packages

Total download size: 276 M
Downloading Packages:
...    
--------------------------------------------------------------------------------
Total                                           5.2 MB/s | 276 MB     00:52     
warning: /var/cache/dnf/group_python-pypy35-67ae7ef39bf64b4c/packages/pypy3-devel-5.10.1-1.fc27.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID 5014e146: NOKEY
Importing GPG key 0x5014E146:
 Userid     : "@python_pypy35 (None) <@python#pypy35@copr.fedorahosted.org>"
 Fingerprint: B075 92F9 BF92 9185 9615 078C 5C1A 0E0A 5014 E146
 From       : https://copr-be.cloud.fedoraproject.org/results/@python/pypy35/pubkey.gpg
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  ... 

Installed:
  findutils.x86_64 1:4.6.0-14.fc27                                              
  gcc.x86_64 7.2.1-2.fc27                                                       
  gcc-c++.x86_64 7.2.1-2.fc27                                                   
  jython.noarch 2.7.1-3.fc27                                                    
  pypy-devel.x86_64 5.8.0-3.fc27                                                
  pypy3-devel.x86_64 5.10.1-1.fc27                                              
  python2-devel.x86_64 2.7.14-6.fc27                                            
  python2-pip.noarch 9.0.1-14.fc27                                              
  python2-virtualenv.noarch 15.1.0-2.fc27                                       
  python26.x86_64 2.6.9-10.fc27                                                 
  python3-devel.x86_64 3.6.3-2.fc27                                             
  python3-tox.noarch 2.7.0-2.fc27                                               
  python33.x86_64 3.3.7-2.fc27                                                  
  python34.x86_64 3.4.7-2.fc27                                                  
  python35.x86_64 3.5.4-2.fc27                                                  
  python37.x86_64 3.7.0-0.1.a2.fc27                                             
  aajohan-comfortaa-fonts.noarch 3.001-1.fc27                                   
  aalto-xml.noarch 1.0.0-3.fc27                                                 
  antlr-tool.noarch 2.7.7-50.fc27                                               
  antlr32-java.noarch 3.2-17.fc27                                               
  apache-commons-compress.noarch 1.14-2.fc27                                    
  binutils.x86_64 2.29-6.fc27                                                   
  bouncycastle.noarch 1.58-1.fc27                                               
  bouncycastle-pkix.noarch 1.58-1.fc27                                          
  copy-jdk-configs.noarch 3.3-2.fc27                                            
  cpp.x86_64 7.2.1-2.fc27                                                       
  dwz.x86_64 0.12-5.fc27                                                        
  fedora-rpm-macros.noarch 26-3.fc27                                            
  fontconfig.x86_64 2.12.6-4.fc27                                               
  fontpackages-filesystem.noarch 1.44-19.fc27                                   
  fpc-srpm-macros.noarch 1.1-3.fc27                                             
  freetype.x86_64 2.8-7.fc27                                                    
  ghc-srpm-macros.noarch 1.4.2-6.fc27                                           
  glibc-devel.x86_64 2.26-15.fc27                                               
  glibc-headers.x86_64 2.26-15.fc27                                             
  gnat-srpm-macros.noarch 4-4.fc27                                              
  go-srpm-macros.noarch 2-10.fc27                                               
  guava.noarch 18.0-11.fc27                                                     
  hamcrest-core.noarch 1.3-21.fc27                                              
  hawtjni-runtime.noarch 1.15-2.fc27                                            
  icu4j.noarch 1:59.1-2.fc27                                                    
  isl.x86_64 0.16.1-3.fc27                                                      
  jansi.noarch 1.16-2.fc27                                                      
  jansi-native.x86_64 1.7-3.fc27                                                
  java-1.8.0-openjdk-headless.x86_64 1:1.8.0.151-1.b12.fc27                     
  javapackages-tools.noarch 5.0.0-7.fc27                                        
  jctools.noarch 2.0.2-2.fc27                                                   
  jffi.x86_64 1.2.12-8.fc27                                                     
  jffi-native.x86_64 1.2.12-8.fc27                                              
  jline.noarch 2.13-10.fc27                                                     
  jnr-constants.noarch 0.9.9-2.fc27                                             
  jnr-ffi.noarch 2.1.6-2.fc27                                                   
  jnr-netdb.noarch 1.1.6-2.fc27                                                 
  jnr-posix.noarch 3.0.41-2.fc27                                                
  jnr-x86asm.noarch 1.0.2-13.fc27                                               
  junit.noarch 1:4.12-7.fc27                                                    
  kernel-headers.x86_64 4.14.13-300.fc27                                        
  libX11.x86_64 1.6.5-4.fc27                                                    
  libX11-common.noarch 1.6.5-4.fc27                                             
  libXau.x86_64 1.0.8-9.fc27                                                    
  libXft.x86_64 2.3.2-7.fc27                                                    
  libXrender.x86_64 0.9.10-4.fc27                                               
  libgomp.x86_64 7.2.1-2.fc27                                                   
  libjpeg-turbo.x86_64 1.5.3-1.fc27                                             
  libmpc.x86_64 1.0.2-8.fc27                                                    
  libpkgconf.x86_64 1.3.12-2.fc27                                               
  libpng.x86_64 2:1.6.31-1.fc27                                                 
  libstdc++-devel.x86_64 7.2.1-2.fc27                                           
  libxcb.x86_64 1.12-5.fc27                                                     
  lksctp-tools.x86_64 1.0.16-8.fc27                                             
  lua.x86_64 5.3.4-5.fc27                                                       
  lua-posix.x86_64 33.3.1-7.fc27                                                
  netty.x86_64 4.1.13-1.fc27                                                    
  nim-srpm-macros.noarch 1-1.fc27                                               
  objectweb-asm.noarch 5.1-8.fc27                                               
  ocaml-srpm-macros.noarch 5-2.fc27                                             
  openblas-srpm-macros.noarch 2-2.fc27                                          
  perl-srpm-macros.noarch 1-24.fc27                                             
  pkgconf.x86_64 1.3.12-2.fc27                                                  
  pkgconf-m4.noarch 1.3.12-2.fc27                                               
  pkgconf-pkg-config.x86_64 1.3.12-2.fc27                                       
  pypy.x86_64 5.8.0-3.fc27                                                      
  pypy-libs.x86_64 5.8.0-3.fc27                                                 
  pypy3.x86_64 5.10.1-1.fc27                                                    
  pypy3-libs.x86_64 5.10.1-1.fc27                                               
  python-rpm-macros.noarch 3-23.fc27                                            
  python-srpm-macros.noarch 3-23.fc27                                           
  python2.x86_64 2.7.14-6.fc27                                                  
  python2-libs.x86_64 2.7.14-6.fc27                                             
  python2-rpm-macros.noarch 3-23.fc27                                           
  python2-setuptools.noarch 37.0.0-1.fc27                                       
  python3-pluggy.noarch 0.3.1-8.fc27                                            
  python3-py.noarch 1.4.34-4.fc27                                               
  python3-rpm-generators.noarch 4.14.0-1.fc27                                   
  python3-rpm-macros.noarch 3-23.fc27                                           
  python3-virtualenv.noarch 15.1.0-2.fc27                                       
  qt5-srpm-macros.noarch 5.9.1-2.fc27                                           
  redhat-rpm-config.noarch 69-1.fc27                                            
  rust-srpm-macros.noarch 5-1.fc27                                              
  stax2-api.noarch 4.0.0-3.fc27                                                 
  stringtemplate.noarch 3.2.1-16.fc27                                           
  tcl.x86_64 1:8.6.7-1.fc27                                                     
  tix.x86_64 1:8.4.3-20.fc27                                                    
  tk.x86_64 1:8.6.7-1.fc27                                                      
  tzdata-java.noarch 2017c-1.fc27                                               
  unzip.x86_64 6.0-36.fc27                                                      
  which.x86_64 2.21-4.fc27                                                      
  xalan-j2.noarch 2.7.1-32.fc27                                                 
  xerces-j2.noarch 2.11.0-29.fc27                                               
  xml-commons-apis.noarch 1.4.01-23.fc27                                        
  xml-commons-resolver.noarch 1.2-23.fc27                                       
  zip.x86_64 3.0-20.fc27                                                        

Upgraded:
  gdbm.x86_64 1:1.13-6.fc27                 python3.x86_64 3.6.3-2.fc27         
  python3-libs.x86_64 3.6.3-2.fc27         

Complete!
22 files removed
 ---> 4069647b5089
Removing intermediate container bd4dbd4aa644
Step 5/6 : ENV LANG C.UTF-8 LC_ALL C.UTF-8
 ---> Running in 30189316be9e
 ---> 917777639ef0
Removing intermediate container 30189316be9e
Step 6/6 : CMD /usr/bin/tox
 ---> Running in 9f56163f726a
 ---> 2824cf34bbc8
Removing intermediate container 9f56163f726a
Successfully built 2824cf34bbc8

[fedora-python-tox ((e711ad3...) %)]$ export TOXENV=pypy3

[fedora-python-tox ((e711ad3...) %)]$ cd example_project

[example_project ((e711ad3...) %)]$ docker run --rm -it -v $PWD:/src -w /src -e TOXENV frenzymadness/fedora-python-tox
ERROR: toxini file 'tox.ini' not found

[example_project ((e711ad3...) %)]$ ls
 fac.py   fac.pyc  'fac$py.class'   __pycache__   test_fac.py  'test_fac$py.class'   tox.ini

[example_project ((e711ad3...) %)]$ sudo setenforce 0

[example_project ((e711ad3...) %)]$ docker run --rm -it -v $PWD:/src -w /src -e TOXENV frenzymadness/fedora-python-tox
ERROR: invocation failed (errno 2), args: ['/src/.tox/pypy3/bin/pip', 'freeze'], cwd: /src
Traceback (most recent call last):
  File "/usr/bin/tox", line 11, in <module>
    load_entry_point('tox==2.7.0', 'console_scripts', 'tox')()
  File "/usr/lib/python3.6/site-packages/tox/session.py", line 39, in main
    retcode = Session(config).runcommand()
  File "/usr/lib/python3.6/site-packages/tox/session.py", line 392, in runcommand
    return self.subcommand_test()
  File "/usr/lib/python3.6/site-packages/tox/session.py", line 557, in subcommand_test
    action=action)
  File "/usr/lib/python3.6/site-packages/tox/venv.py", line 412, in _pcall
    redirect=redirect, ignore_ret=ignore_ret)
  File "/usr/lib/python3.6/site-packages/tox/session.py", line 140, in popen
    stdout=stdout, stderr=STDOUT)
  File "/usr/lib/python3.6/site-packages/tox/session.py", line 228, in _popen
    stdout=stdout, stderr=stderr, env=env)
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/src/.tox/pypy3/bin/pip': '/src/.tox/pypy3/bin/pip'

[example_project ((e711ad3...) %)]$ rm .tox/ -rf

[example_project ((e711ad3...) %)]$ docker run --rm -it -v $PWD:/src -w /src -e TOXENV frenzymadness/fedora-python-tox
pypy3 create: /src/.tox/pypy3
pypy3 installdeps: pytest < 3.3
pypy3 installed: cffi==1.11.2,greenlet==0.4.12,py==1.5.2,pytest==3.2.5,readline==6.2.4.1
pypy3 runtests: PYTHONHASHSEED='2917983896'
pypy3 runtests: commands[0] | pytest
====================================================================================================== test session starts ======================================================================================================
platform linux -- Python 3.5.3[pypy-5.10.1-final], pytest-3.2.5, py-1.5.2, pluggy-0.4.0
rootdir: /src, inifile:
collected 0 items / 1 errors                                                                                                                                                                                                     

============================================================================================================ ERRORS =============================================================================================================
_________________________________________________________________________________________________ ERROR collecting test_fac.py __________________________________________________________________________________________________
import file mismatch:
imported module 'test_fac' has this __file__ attribute:
  .../fedora-python-tox/example_project/test_fac.py
which is not the same as the test file we want to collect:
  /src/test_fac.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================================================================================== 1 error in 0.47 seconds ====================================================================================================
ERROR: InvocationError: '/src/.tox/pypy3/bin/pytest'
____________________________________________________________________________________________________________ summary ____________________________________________________________________________________________________________
ERROR:   pypy3: commands failed

[example_project ((e711ad3...) %)]$ find -name __pycache__
./__pycache__
./.tox/pypy3/lib-python/3/__pycache__
...

[example_project ((e711ad3...) %)]$ rm .tox/ -rf
snip a lot of Permission denied

[example_project ((e711ad3...) %)]$ sudo rm .tox/ -rf

[example_project ((e711ad3...) %)]$ find -name __pycache__
./__pycache__

[example_project ((e711ad3...) %)]$ rm __pycache__/ -rf

[example_project ((e711ad3...) %)]$ docker run --rm -it -v $PWD:/src -w /src -e TOXENV frenzymadness/fedora-python-tox
pypy3 create: /src/.tox/pypy3
pypy3 installdeps: pytest < 3.3
pypy3 installed: cffi==1.11.2,greenlet==0.4.12,py==1.5.2,pytest==3.2.5,readline==6.2.4.1
pypy3 runtests: PYTHONHASHSEED='3295939561'
pypy3 runtests: commands[0] | pytest
====================================================================================================== test session starts ======================================================================================================
platform linux -- Python 3.5.3[pypy-5.10.1-final], pytest-3.2.5, py-1.5.2, pluggy-0.4.0
rootdir: /src, inifile:
collected 10 items                                                                                                                                                                                                               

test_fac.py ..........

=================================================================================================== 10 passed in 0.07 seconds ===================================================================================================
____________________________________________________________________________________________________________ summary ____________________________________________________________________________________________________________
  pypy3: commands succeeded
  congratulations :)

[example_project ((e711ad3...) %)]$ sudo setenforce 1
```

**Comment by hroncok** [comment]
Any chance you had your `.tox` dir with previous pypy3 env? Unfortunately pypy (2 and 3) venvs need to be recreated on each upgrade, that's why I upgrade pypy3 only in rawhide + copr.

**Comment by frenzymadness** [comment]
Hmm, yes, it seems that it was caused by forgotten .tox folder from one of the previous build. I'll revert my change.
